=== billy-le/billyle.dev/.astro/collections/projects.schema.json
{
  "$ref": "#/definitions/projects",
  "definitions": {
    "projects": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "link": {
          "anyOf": [
            {
              "type": "string",
              "format": "uri"
            },
            {
              "type": "null"
            }
          ]
        },
        "images": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "src": {
                "type": "string"
              },
              "alt": {
                "type": "string"
              }
            },
            "required": [
              "src",
              "alt"
            ],
            "additionalProperties": false
          },
          "default": []
        },
        "sourceCode": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "link": {
                "type": "string",
                "format": "uri"
              },
              "host": {
                "type": "string"
              }
            },
            "required": [
              "link",
              "host"
            ],
            "additionalProperties": false
          }
        },
        "tags": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "default": []
        },
        "ranking": {
          "type": "string"
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "description",
        "link",
        "sourceCode",
        "ranking"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== billy-le/billyle.dev/packages/website/src/content/projects/zennami.json
{
  "name": "ZenNami",
  "description": "ZenNami brings lo-fi radio and ambient soundscapes as browser extension. Developed using the browser-wxt package to streamline cross-browser compability development. The radio stations are powered by the Radio Browser Network and features station management via liking and hiding stations, adding 8 different ambient textures to zone in, and using browser storage so data is private to the user.",
  "link": "https://zennami.com",
  "images": [
    {
      "src": "./_images/zennami-home.webp",
      "alt": "ZenNami browser extension home screen"
    },
    {
      "src": "./_images/zennami-favorite-stations.webp",
      "alt": "A list of favorited stations by liking the station"
    },
    {
      "src": "./_images/zennami-hidden-stations.webp",
      "alt": "A list of hidden stations to unhide stations"
    },
    {
      "src": "./_images/zennami-playlist-multi.webp",
      "alt": "A list of multi-channel radio stations"
    },
    {
      "src": "./_images/zennami-playlist-single.webp",
      "alt": "A list of single channel radio stations"
    },
    {
      "src": "./_images/zennami-landing.webp",
      "alt": "ZenNami Landing Page"
    }
  ],
  "sourceCode": [],
  "tags": [
    "browser-wxt",
    "tanstack start",
    "react",
    "tailwind",
    "cloudflare workers",
    "web apis"
  ],
  "ranking": "high"
}

=== billy-le/billyle.dev/packages/website/src/content/projects/clearbank.json
{
  "name": "ClearBank",
  "description": "ClearBank is a financial banking app that uses Plaid to connect to your bank accounts and shows your current balance, transaction history, and spending budget. It uses Dwolla to transfer funds from one account to another via a shareable link.",
  "link": "https://clearbank.billyle.dev",
  "images": [
    {
      "src": "./_images/clearbank-login.webp",
      "alt": "clearbank login page"
    },
    {
      "src": "./_images/clearbank-dashboard.webp",
      "alt": "clearbank dashboard"
    },
    {
      "src": "./_images/clearbank-accounts.webp",
      "alt": "clearbank accounts page"
    },
    {
      "src": "./_images/clearbank-transactions.webp",
      "alt": "clearbank transactions page"
    },
    {
      "src": "./_images/clearbank-transfers.webp",
      "alt": "clearbank transfers page"
    },
    {
      "src": "./_images/clearbank-plaid.webp",
      "alt": "clearbank plaid integration"
    }
  ],
  "sourceCode": [
    { "link": "https://github.com/billy-le/clearbank", "host": "github" }
  ],
  "tags": ["nextjs", "react", "plaid", "dwolla", "tailwind"],
  "ranking": "low"
}

=== billy-le/billyle.dev/packages/website/src/content/projects/converse.json
{
  "name": "Converse",
  "description": "Converse is a real-time web chat app utilizing WebRTC and Socket.io. It boasts features such as public chatrooms, live video and audio streaming, the ability to change input/output media devices, and invitation link sharing. I initiated this project with the primary goal of enhancing my knowledge in real-time web communications and protocols.",
  "link": "https://converse.billyle.dev",
  "images": [
    {
      "src": "./_images/converse-lobby-01.webp",
      "alt": "converse user 1 lobby"
    },
    {
      "src": "./_images/converse-lobby-02.webp",
      "alt": "converse user 2 lobby"
    },
    {
      "src": "./_images/converse-chatroom.webp",
      "alt": "converse chatroom"
    },
    {
      "src": "./_images/converse-livestream.webp",
      "alt": "converse livestream"
    }
  ],
  "sourceCode": [
    { "link": "https://github.com/billy-le/converse", "host": "github" }
  ],
  "tags": ["node", "express", "liquidjs", "web-rtc", "socket.io"],
  "ranking": "low"
}

=== billy-le/billyle.dev/packages/website/src/content/projects/is-the-casino-open.json
{
  "name": "Is the Casino Open?",
  "description": "Developed a full-stack application that bridges the gap between social media sentiment and real-time market data, allowing users to track trending assets and engage with the market through a gamified interface. This was a fun project that is completely useless. I wanted to capture the same gambling culture as WallStreetBets where individual would randomly \"YOLO\" their savings on trending stocks.",
  "link": "https://isthecasinoopen.com",
  "images": [
    {
      "src": "./_images/casino-open-home-page.png",
      "alt": "is the casino open - homepage"
    },
    {
      "src": "./_images/casino-open-betting.png",
      "alt": "is the casino open - betting"
    },
    {
      "src": "./_images/casino-open-live-charts.png",
      "alt": "is the casino open - live charts"
    }
  ],
  "sourceCode": [],
  "tags": [
    "react",
    "tanstack start",
    "tailwind",
    "web sockets",
    "redis",
    "postresql",
    "docker"
  ],
  "ranking": "high"
}

=== billy-le/billyle.dev/src/content/projects/dotted-earth.json
{
  "name": "Dotted",
  "description": "An AI mobile application built on Flutter, Supabase, and Node. The app generates an itinerary for a user based on their profile. The AI takes in account of their recreational activities, diet, favorite cuisines, and food allergies which then creates a schedule. A user can then view the itinerary which will show each location and routes on a Google Map.",
  "link": null,
  "images": [],
  "sourceCode": [
    { "link": "https://github.com/dotted-earth/dotted", "host": "github" },
    { "link": "https://github.com/dotted-earth/dotted-api", "host": "github" },
    { "link": "https://github.com/dotted-earth/dotted-web", "host": "github" },
    { "link": "https://github.com/dotted-earth/dotted-crew", "host": "github" }
  ],
  "tags": ["flutter", "dart", "ai", "supabase", "node", "python"],
  "ranking": "low"
}

=== billy-le/billyle.dev/src/content/projects/clearbank.json
{
	"name": "ClearBank",
	"description": "ClearBank is a financial banking app that uses Plaid to connect to your bank accounts and shows your current balance, transaction history, and spending budget. It uses Dwolla to transfer funds from one account to another via a shareable link.",
	"link": "https://clearbank.billyle.dev",
	"images": [
		{
			"src": "./_images/clearbank-login.png",
			"alt": "clearbank login page"
		},
		{
			"src": "./_images/clearbank-dashboard.png",
			"alt": "clearbank dashboard"
		},
		{
			"src": "./_images/clearbank-accounts.png",
			"alt": "clearbank accounts page"
		},
		{
			"src": "./_images/clearbank-transactions.png",
			"alt": "clearbank transactions page"
		},
		{
			"src": "./_images/clearbank-transfers.png",
			"alt": "clearbank transfers page"
		},
		{
			"src": "./_images/clearbank-plaid.png",
			"alt": "clearbank plaid integration"
		}
	],
	"sourceCode": [
		{ "link": "https://github.com/billy-le/clearbank", "host": "github" }
	],
	"tags": ["nextjs", "react", "plaid", "dwolla", "tailwind"],
	"ranking": "low"
}

=== billy-le/billyle.dev/src/content/projects/converse.json
{
  "name": "Converse",
  "description": "Converse is a real-time web chat app utilizing WebRTC and Socket.io. It boasts features such as public chatrooms, live video and audio streaming, the ability to change input/output media devices, and invitation link sharing. I initiated this project with the primary goal of enhancing my knowledge in real-time web communications and protocols.",
  "link": "https://converse.billyle.dev",
  "images": [],
  "sourceCode": [
    { "link": "https://github.com/billy-le/converse", "host": "github" }
  ],
  "tags": ["node", "express", "liquidjs", "web-rtc", "socket.io"],
  "ranking": "low"
}

=== billy-le/billyle.dev/packages/website/src/content/projects/soil-life.json
{
  "name": "Soil Life",
  "description": "I developed an informational website aimed at educating the public about soil life, employing the JAMStack architecture. Initially, the project began as a monolithic stack with static pages served from an Express Node server using Embedded JavaScript Templates (ejs). Eventually, the final product transitioned to React, leveraging Google Sheets as the CMS.",
  "link": "https://soillife.org",
  "images": [
    {
      "src": "./_images/soillife-home.webp",
      "alt": "soil life home page"
    },
    {
      "src": "./_images/soillife-web-of-soil.webp",
      "alt": "soil life - web of soil"
    },
    {
      "src": "./_images/soillife-web-graph.webp",
      "alt": "soil life - web graph"
    },
    {
      "src": "./_images/soillife-media.webp",
      "alt": "soil life - media page"
    },
    {
      "src": "./_images/soillife-101.webp",
      "alt": "soil life - soil 101 page"
    }
  ],
  "sourceCode": [
    { "link": "https://github.com/SoilLife/soil-life-web", "host": "github" }
  ],
  "tags": ["react", "nextjs", "netlify", "tailwind"],
  "ranking": "mid"
}
