=== billy-le/billyle.dev/.astro/collections/projects.schema.json
{
  "$ref": "#/definitions/projects",
  "definitions": {
    "projects": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "link": {
          "anyOf": [
            {
              "type": "string",
              "format": "uri"
            },
            {
              "type": "null"
            }
          ]
        },
        "images": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "src": {
                "type": "string"
              },
              "alt": {
                "type": "string"
              }
            },
            "required": [
              "src",
              "alt"
            ],
            "additionalProperties": false
          },
          "default": []
        },
        "sourceCode": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "link": {
                "type": "string",
                "format": "uri"
              },
              "host": {
                "type": "string"
              }
            },
            "required": [
              "link",
              "host"
            ],
            "additionalProperties": false
          }
        },
        "tags": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "default": []
        },
        "ranking": {
          "type": "string"
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "description",
        "link",
        "sourceCode",
        "ranking"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== billy-le/billyle.dev/src/content/projects/eventlulu.json
{
	"name": "Eventlulu",
	"description": "Eventlulu is an online event management platform for hotels. It features a dashboard with important metrics, creating proposals from leads, and an admin page to inventory products and services offered. I started this project to assist the daily operations of a hotel where majority of their sales pipeline is done by paper and hand.",
	"link": "https://eventlulu.billyle.dev",
	"images": [
		{
			"src": "./_images/eventlulu-home.png",
			"alt": "eventlulu home page"
		},
		{
			"src": "./_images/eventlulu-dashboard.png",
			"alt": "eventlulu dashboard page"
		},
		{
			"src": "./_images/eventlulu-charts.png",
			"alt": "eventlulu charst"
		},
		{
			"src": "./_images/eventlulu-lead-form.png",
			"alt": "eventlulu lead form"
		},
		{
			"src": "./_images/eventlulu-leads.png",
			"alt": "eventlulu leads table"
		}
	],
	"sourceCode": [
		{ "link": "https://github.com/billy-le/eventlulu", "host": "github" }
	],
	"tags": ["node", "trpc", "typescript", "tailwindcss", "react"],
	"ranking": "high"
}

=== billy-le/billyle.dev/packages/website/src/content/projects/dotted-earth.json
{
  "name": "Dotted",
  "description": "An AI-powered mobile application built using Flutter, Supabase, and Node. The app generates an itinerary for users based on their profiles. The AI takes into account their recreational activities, diet, favorite cuisines, and food allergies to create a personalized schedule. Users can then view the itinerary, which displays each location and route on Google Maps.",
  "link": "https://billyle.dev/posts/case-study-building-dotted",
  "images": [
    {
      "src": "./_images/dotted-desktop.webp",
      "alt": "dotted landing page"
    },
    {
      "src": "./_images/dotted-screens.webp",
      "alt": "dotted various screens"
    },
    {
      "src": "./_images/excalidraw_dotted.webp",
      "alt": "dotted app design and logic flow"
    },
    {
      "src": "./_images/dotted-login.gif",
      "alt": "dotted login flow"
    },
    {
      "src": "./_images/dotted-on-boarding.gif",
      "alt": "dotted onboarding flow"
    },
    {
      "src": "./_images/dotted-generate-itinerary.gif",
      "alt": "dotted generating itineraries"
    },
    {
      "src": "./_images/dotted-view-itinerary.gif",
      "alt": "dotted view trip itinerary"
    }
  ],
  "sourceCode": [
    { "link": "https://github.com/dotted-earth", "host": "github" }
  ],
  "tags": ["flutter", "dart", "ai", "supabase", "node", "python"],
  "ranking": "low"
}

=== billy-le/billyle.dev/packages/website/src/content/projects/eventlulu.json
{
  "name": "Eventlulu",
  "description": "Eventlulu is an online event management platform for hotels. It features a dashboard with important metrics, creating proposals from leads, and an admin page to inventory products and services offered. I started this project to assist the daily operations of a hotel where majority of their sales pipeline is done by paper and hand.",
  "link": "https://eventlulu.billyle.dev",
  "images": [
    {
      "src": "./_images/eventlulu-home.webp",
      "alt": "eventlulu home page"
    },
    {
      "src": "./_images/eventlulu-dashboard.webp",
      "alt": "eventlulu dashboard page"
    },
    {
      "src": "./_images/eventlulu-charts.webp",
      "alt": "eventlulu charst"
    },
    {
      "src": "./_images/eventlulu-lead-form.webp",
      "alt": "eventlulu lead form"
    },
    {
      "src": "./_images/eventlulu-leads.webp",
      "alt": "eventlulu leads table"
    }
  ],
  "sourceCode": [
    { "link": "https://github.com/billy-le/eventlulu", "host": "github" }
  ],
  "tags": ["node", "trpc", "typescript", "tailwindcss", "react"],
  "ranking": "low"
}
